# Criação do menu principal
print('-----------------------------------------------------\n')
print('  BEM-VINDO AO SISTEMA DE GERENCIAMENTO DE LIVRARIA  \n')
print('-----------------------------------------------------')
print('                    --- MENU ---                     ')
print('-----------------------------------------------------')
print(':   1 -> Adicionar Livro                            :')
print(':   2 -> Listar Livros                              :')
print(':   3 -> Buscar Livro                               :')
print(':   4 -> Editar Dados                               :')
print(':   5 -> Excluir Livro                              :')
print(':   6 -> Salvar Dados                               :')
print(':   7 -> Carregar Dados                             :')
print(':   8 -> Sair                                       :')
print('-----------------------------------------------------')